# Generated by Django 6.0.3 on 2026-03-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(error_messages={'unique': 'already exists'}, max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
